FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV DD_SERVICE="thread-leaky-api-python"
ENV DD_ENV="prod"
LABEL com.datadoghq.tags.service="thread-leaky-api-python"
LABEL com.datadoghq.tags.env="prod"

COPY src/python/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY src/python/thread_leaky_server.py /app/

EXPOSE 9086

CMD ["ddtrace-run", "python", "thread_leaky_server.py"]
