services:
  mongodb:
    image: mongo:5
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017

  ddagent:
    image: datadog/agent:latest
    environment:
      - DD_HOSTNAME=github-actions-worker
      - DD_BIND_HOST=0.0.0.0
      - DD_REMOTE_CONFIGURATION_ENABLED=true
      - DD_SITE=datad0g.com
      - DD_API_KEY=
      - DD_REMOTE_CONFIGURATION_KEY=${DD_REMOTE_CONFIGURATION_KEY-invalid_but_this_is_fine}
      - DD_REMOTE_CONFIGURATION_REFRESH_INTERVAL=5s
      - DD_APM_RECEIVER_SOCKET=/tmp/ddagent/trace.sock
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    ports:
      - 8126:8126
      - 8125:8125/udp
    volumes:
      - ddagent:/tmp/ddagent:rw

  movies-api-python:
    build:
      context: .
      dockerfile: python-app/Dockerfile
    ports:
      - 8080:8080
    environment:
      DD_AGENT_HOST: "ddagent"
      DD_SERVICE: "movies-api-python"
      DD_ENV: "prod"
      DD_PROFILING_ENABLED: "true"
      MONGO_URI: mongodb://mongodb:27017
      MOVIES_API_PORT: 8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - ddagent
      - mongodb
    restart: always

volumes:
  ddagent:
