apiVersion: v1
kind: Service
metadata:
  name: native-leaky-api-python
  namespace: profiling-demo
spec:
  selector:
    app: native-leaky-api-python
  ports:
    - port: 9088
      targetPort: 9088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: native-leaky-api-python
  namespace: profiling-demo
  labels:
    tags.datadoghq.com/env: prod
    tags.datadoghq.com/service: native-leaky-api-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: native-leaky-api-python
  template:
    metadata:
      labels:
        app: native-leaky-api-python
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: native-leaky-api-python
      annotations:
        ad.datadoghq.com/native-leaky-api-python.logs: '[{"source":"python","service":"native-leaky-api-python"}]'
    spec:
      containers:
        - name: native-leaky-api-python
          image: native-leaky-api-python:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9088
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_PROFILING_UPLOAD_PERIOD
              value: "10"
            - name: DD_ENV
              value: "prod"
            - name: DD_SERVICE
              value: "native-leaky-api-python"
            - name: DD_TAGS
              value: "env:prod"
            - name: DD_ENTITY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: MOVIES_API_PORT
              value: "9088"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 9088
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9088
            initialDelaySeconds: 10
            periodSeconds: 30
